# Generated by Django 4.2 on 2023-05-01 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_alter_album_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={},
        ),
    ]
