# Generated by Django 4.2 on 2023-05-01 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_alter_song_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={},
        ),
    ]
